### ISSUE TITLE
Something went wrong, something went wrong, something went wrong...

### ISSUE THREAD

**Issue by HunterGraubard** [Schwaxx/WFInfo#9]
I've enjoyed using WFInfo, but this is starting to get really frustrating now instead of helping me. I clear a fissure, press Print Screen to see the information to help me make a decision, and instead I get a pop up saying... "Something went wrong". Press Print Screen again. "Something went wrong". Print Screen. "Something went wrong". "Something went wrong". "Something went wrong". And then the reward screen ends and I don't get to choose.

Something seems to go wrong more often than not, especially lately. Why is this happening? It doesn't even tell me what went wrong. Just "something".

**Comment by Schwaxx** [comment]
The reason that it doesn't provide all of the info is because it could be one of many different things,
and unless you're able to program this yourself you don't need the that information.

It does store more information in the log however, which you should post here or on the help page form.

It can be found here: 
%AppData%\WFInfo

**Comment by idSmoker** [comment]
I'm also getting the "Something went wrong" error and the information in the error log suggests that format of the return you're getting has changed.

The detailed exception log looks like:
`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at WFInfo.Glob.GetPlat(String str, Boolean getUser, Boolean getMod, Boolean getID, Boolean getDif)
   at WFInfo.Main.bgPPrice_DoWork(Object sender, DoWorkEventArgs e)`

**Comment by Schwaxx** [comment]
In response to idSmoker:

You aren't the only person I've seen with this issue, however the warframe.market API is still working just as it has. I suspect what is happening is for some reason your computers are sending  out a malformed request to the API and when I try to treat the response as I would any other, it throws this error.

Try enable debug mode and running the application a few times. If inside of the debug/test folder are images of anything but the part text, it is likely a resolution issue.

It could however be something completely different but it would be hard to debug without more information, as like I said, it is still working for the vast majority of users.

**Comment by idSmoker** [comment]
I've reported the bug via your google site, and included a copy of the WFInfo.log file generated by 3 runs with the error while debug mode was activated.

In the case of these runs, there were no other files/folders created, but I have seen them before.

**Comment by Schwaxx** [comment]
I'm not prepared to fix your problem right now, but maybe in a week or so I can help you fix this.

But for now there is nothing I can do.

**Comment by miffels** [comment]
I just submitted a report, but looking at the logs this is exactly what's happening for me as well... Looks like it's trying to parse some HTML/XML error reply as JSON...? Enabling debug mode doesn't seem to add anything to the WFInfo folder. Wouldn't it make sense to log the request/response when communication-related issues happen?
